# Generated by Django 2.2.12 on 2020-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('meta', models.CharField(default='{\\“github\\”:"",\\“linkedin\\”:"",\\“twitter\\”:""}', max_length=400)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
