# Generated by Django 2.2.12 on 2020-04-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200413_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordSalt',
        ),
    ]
